mod assign_op;
mod binary_op;
mod expr;
mod fn_param;
mod fn_signature;
mod group_rule;
mod program;
mod stmt;
mod struct_field;
mod ty;
mod unary_op;
mod which_clause;
mod parse_error;

pub use assign_op::AssignOp;
pub use binary_op::BinaryOp;
pub use expr::Expr;
pub use fn_param::FnParam;
pub use fn_signature::FnSignature;
pub use group_rule::GroupRule;
pub use program::Program;
pub use stmt::Stmt;
pub use struct_field::StructField;
pub use ty::Type;
pub use unary_op::UnaryOp;
pub use which_clause::WhichClause;
pub use parse_error::ParseError;
use crate::modules::implements::tokens::SpannedToken;

pub type PInput<'a> = &'a [SpannedToken];
